backend:
  provider: glm # ollama, gpt, gpt4, deepseek, gemini, mixed, qwen, ernie, glm, spark, hunyuan
  google_api_key: YOUR_GOOGLE_API_KEY_HERE # only for gemini
  openai_api_key: YOUR_OPENAI_KEY_HERE # only for openai
  deepseek_api_key: YOUR_DEEPSEEK_API_KEY_HERE # only for deepseek
  qwen_api_key: YOUR_QWEN_API_KEY_HERE # only for qwen
  QIANFAN_ACCESS_KEY: YOUR_QIANFAN_ACCESS_KEY_HERE # only for baidu qianfan
  QIANFAN_SECRET_KEY: YOUR_QIANFAN_SECRET_KEY_HERE # only for baidu qianfan
  glm_api_key: YOUR_GLM_API_KEY_HERE # only for glm
  hunyuan_api_key: YOUR_HUANYUAN_API_KEY_HERE # only for hunyuan
  spark_api_key: YOUR_SPARK_API_KEY_HERE # only for spark
  ollama_model_name: qwen2:7b # only for ollama
  base_url: # only for openai-compatible api
website:
  host: 0.0.0.0
  port: 5050
  flask_secret: iAgents
mysql:
  host: localhost
  username: YOUR_MYSQL_USERNAME_HERE
  password: YOUR_MYSQL_PASSWORD_HERE
  database: YOUR_MYSQL_DATABASE_HERE
logging:
  level: INFO
  logname: test
agent:
  max_query_retry_times: 1
  max_communication_turns: 3
  max_tool_retry_times: 1
  rewrite_prompt: False
  use_llamaindex: True
mode:
  mode: Base # Base, RAG
